/**
 * migrate-legacy/config.ts — knobs for the OLD-app → NEW-app data migration.
 *
 * Everything here is a deliberate, owner-confirmable decision. Nothing about the
 * old data's shape is assumed silently — where the mapping is a judgement call
 * (roles, agent source), it lives here and the reconciliation report flags it.
 */

/**
 * Interest freeze/recompute anchor.
 *
 * Owner rule: "Already paid interest until June will stay as is. July interest
 * will be calculated from June 29 to July 28 for all existing as well as new
 * customers."
 *
 * This is the LAST already-paid 28th. The recompute passes it to the interest
 * engine as `interestStartDate`, so the first regenerated payout lands on the
 * next 28th (2026-07-28) covering Jun-29 → Jul-28 = 30 actual days. Every old
 * schedule row dated on/before this anchor is FROZEN verbatim (money that moved);
 * every unpaid row after it is dropped and regenerated by the new engine.
 *
 * Change this one constant to re-anchor the migration to a different month.
 */
export const INTEREST_ANCHOR = '2026-06-28';

/** Old app stored money as rupees NUMERIC(18,2); new app persists rupees too
 * (paise is internal to the math layer). So money copies 1:1 — no scaling. */
export const MONEY_SCALE = 1;

/**
 * Old role name → new role name. The new app has exactly 8 roles. Several old
 * roles collapse. These are DEFAULTS — the report prints the resolved mapping
 * and every unmapped old role so the owner can correct before the real load.
 */
export const ROLE_MAP: Record<string, string> = {
  super_admin: 'super_admin',
  admin: 'admin',
  cxo: 'cxo',
  wealth_manager: 'ncd_manager',
  reports_manager: 'branch_manager',
  ho_admin: 'ncd_manager',
  finance: 'ncd_manager',
  branch_executive: 'branch_staff',
  agent: 'agent',
  customer: 'customer',
};

/** Fallback new-role when an old role name isn't in ROLE_MAP. Flagged in report. */
export const ROLE_FALLBACK = 'branch_staff';

/** Old agents.commission_eligibility_status → new agents.commission_status. */
export const AGENT_COMMISSION_STATUS_MAP: Record<string, string> = {
  NotEligible: 'None',
  PendingApproval: 'PendingApproval',
  Approved: 'Approved',
  Rejected: 'Revoked',
};

/**
 * Old application statuses that carry a live/paid interest schedule and whose
 * FUTURE (unpaid) rows should be recomputed. Everything else keeps its old
 * schedule frozen verbatim (matured/redeemed history never changes).
 */
export const RECOMPUTE_APP_STATUSES = new Set(['Active']);

/** Old due_type → new due_type. Old 'Final' meant the principal-return row. */
export const DUE_TYPE_MAP: Record<string, string> = {
  Interest: 'Interest',
  BrokenInterest: 'BrokenInterest',
  Redemption: 'Redemption',
  Final: 'Redemption',
  Premature: 'Premature',
  Rollover: 'Redemption',
};

/** Old schedule.status → new schedule.status (new set: Scheduled|Paid|Failed|Skipped). */
export const SCHEDULE_STATUS_MAP: Record<string, string> = {
  Scheduled: 'Scheduled',
  Released: 'Scheduled',
  Paid: 'Paid',
  Failed: 'Failed',
  Skipped: 'Skipped',
};

/** Standard TDS rate (%) used when recomputing future interest rows, when the
 * old data doesn't carry a per-row rate. Sourced from the new app's seeded
 * tds_rules at load time; this is only the ultimate fallback. */
export const DEFAULT_TDS_RATE_PCT = 10;
